version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - .env
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs
    ports:
    - "8000:8000" 

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped